/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

import Business.Parroquia;
import javax.swing.JOptionPane;

/**
 *
 * @author Camilo
 */
public class FormMain extends javax.swing.JFrame {
    
Parroquia myParroquia;
    /**
     * Creates new form FormMain
     */
    public FormMain() {
        this.myParroquia=new Parroquia();
        initComponents();
        this.txtValorDiezmo.setEditable(false);
        this.txtInfo.setEditable(false);
    }

    
    private void limpiar(){
        
        this.txtNombre.setText("");
        this.txtCedula.setText("");
        this.txtDireccion.setText("");
        this.txtTelefono.setText("");
        this.cmbEstrato.setSelectedIndex(0);
        this.txtInfo.setText("");
     this.txtCedulaFiel.setText("");
     this.txtValorDiezmo.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        cmbGuardarFiel = new javax.swing.JButton();
        cmbModificarFiel = new javax.swing.JButton();
        cmbEliminarFiel = new javax.swing.JButton();
        cmbBuscarFiel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbEstrato = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        txtCedulaFiel = new javax.swing.JTextField();
        txtValorDiezmo = new javax.swing.JTextField();
        cmbConsultarDiezmo = new javax.swing.JButton();
        cmbPagarDiezmo = new javax.swing.JButton();
        cmbTotalDiezmo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInfo = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        cmbGuardarFiel.setText("Guardar");
        cmbGuardarFiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGuardarFielActionPerformed(evt);
            }
        });

        cmbModificarFiel.setText("Modificar");
        cmbModificarFiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbModificarFielActionPerformed(evt);
            }
        });

        cmbEliminarFiel.setText("Eliminar");
        cmbEliminarFiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEliminarFielActionPerformed(evt);
            }
        });

        cmbBuscarFiel.setText("Buscar");
        cmbBuscarFiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBuscarFielActionPerformed(evt);
            }
        });

        jLabel2.setText("Cedula:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Direccion:");

        jLabel5.setText("Telefono:");

        jLabel6.setText("Estrato:");

        cmbEstrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(txtCedula)
                    .addComponent(cmbGuardarFiel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbModificarFiel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbEliminarFiel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbBuscarFiel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbEstrato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(11, 11, 11)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbEstrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(cmbGuardarFiel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbModificarFiel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbEliminarFiel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbBuscarFiel)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        cmbConsultarDiezmo.setText("Consultar");
        cmbConsultarDiezmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbConsultarDiezmoActionPerformed(evt);
            }
        });

        cmbPagarDiezmo.setText("Pagar");
        cmbPagarDiezmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPagarDiezmoActionPerformed(evt);
            }
        });

        cmbTotalDiezmo.setText("Totalizar");
        cmbTotalDiezmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTotalDiezmoActionPerformed(evt);
            }
        });

        jLabel7.setText("Cedula:");

        jLabel8.setText("Valor Diezmo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtValorDiezmo, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                        .addComponent(txtCedulaFiel, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                        .addComponent(cmbConsultarDiezmo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbPagarDiezmo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbTotalDiezmo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCedulaFiel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValorDiezmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(cmbConsultarDiezmo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbPagarDiezmo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTotalDiezmo)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        txtInfo.setColumns(20);
        txtInfo.setRows(5);
        jScrollPane1.setViewportView(txtInfo);

        jLabel1.setText("Parroquia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel1)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbGuardarFielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGuardarFielActionPerformed
        // TODO add your handling code here:
        String nombre=this.txtNombre.getText();
        String cedula=this.txtCedula.getText();
        String direccion=this.txtDireccion.getText();
        String telefono=this.txtTelefono.getText();
        String estrato=String.valueOf(this.cmbEstrato.getSelectedItem());
        
        if("".equals(cedula)||"".equals(nombre)||"".equals(direccion)||
           "".equals(telefono)||"Seleccione".equals(estrato)){
            JOptionPane.showMessageDialog(null, "Rellene los campos");
        }else{
            String c=this.myParroquia.registrarFiel(cedula, nombre, telefono, direccion, estrato);
            JOptionPane.showMessageDialog(null,c);
            this.limpiar();
        }
        
    }//GEN-LAST:event_cmbGuardarFielActionPerformed

    private void cmbModificarFielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbModificarFielActionPerformed
        // TODO add your handling code here:
        
        String nombre=this.txtNombre.getText();
        String cedula=this.txtCedula.getText();
        String direccion=this.txtDireccion.getText();
        String telefono=this.txtTelefono.getText();
        String estrato=String.valueOf(this.cmbEstrato.getSelectedItem());
        
        if("".equals(cedula)||"".equals(nombre)||"".equals(direccion)||
           "".equals(telefono)||"Seleccione".equals(estrato)){
            JOptionPane.showMessageDialog(null, "Rellene los campos");
        }else{
            String c=this.myParroquia.modificarFiel(cedula, nombre, telefono, direccion, estrato);
            JOptionPane.showMessageDialog(null,c);
            this.limpiar();
        }
        
        
    }//GEN-LAST:event_cmbModificarFielActionPerformed

    private void cmbBuscarFielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBuscarFielActionPerformed
        // TODO add your handling code here:
        
        String cedula=this.txtCedula.getText();
        
        if("".equals(cedula)){
            JOptionPane.showMessageDialog(null, "Digita la cedula del fiel");
        }else{
            String [] c=this.myParroquia.consultarFiel(cedula).split("-");
            if(c[0].equals("Fiel no existe")){
                JOptionPane.showMessageDialog(null, c[0]);
            }else{
            this.txtNombre.setText(c[1]);
            this.txtDireccion.setText(c[2]);
            this.txtTelefono.setText(c[3]);
            this.cmbEstrato.setSelectedIndex(Integer.parseInt(c[4]));
            this.txtInfo.setText(c[1]+" se encuentra como: "+c[5]);
            } 
        }
        
    }//GEN-LAST:event_cmbBuscarFielActionPerformed

    private void cmbEliminarFielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEliminarFielActionPerformed
        // TODO add your handling code here:
        
        String cedula=this.txtCedula.getText();
        
        if("".equals(cedula)){
            JOptionPane.showMessageDialog(null, "Digita la cedula del fiel que desea eliminar");
        }else{
            String  c=this.myParroquia.eliminarFiel(cedula);
            JOptionPane.showMessageDialog(null, c);
            this.limpiar();
        }
        
        
    }//GEN-LAST:event_cmbEliminarFielActionPerformed

    private void cmbConsultarDiezmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbConsultarDiezmoActionPerformed
        // TODO add your handling code here:
        
        String cedula=this.txtCedulaFiel.getText();
        
        if("".equals(cedula)){
            JOptionPane.showMessageDialog(null, "Digita la cedula del fiel que desea consultar");
        }else{
            String  c=this.myParroquia.consultarDiezmo(cedula);
            if("Fiel no existe".equals(c)){
                JOptionPane.showMessageDialog(null, c);
            }else{
                this.txtValorDiezmo.setText(c); 
            }
           
        }
        
        
    }//GEN-LAST:event_cmbConsultarDiezmoActionPerformed

    private void cmbPagarDiezmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPagarDiezmoActionPerformed
        // TODO add your handling code here:
        
        String cedula=this.txtCedulaFiel.getText();
        String valorDiezmo=this.txtValorDiezmo.getText();
        
        if("".equals(cedula)||"".equals(valorDiezmo)){
            JOptionPane.showMessageDialog(null, "Digita la cedula y el valor a pagar");
        }else{
            String  c=this.myParroquia.pagarDiezmo(cedula ,valorDiezmo);
             JOptionPane.showMessageDialog(null, c);
             this.limpiar();
        }
         

    }//GEN-LAST:event_cmbPagarDiezmoActionPerformed

    private void cmbTotalDiezmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTotalDiezmoActionPerformed
        // TODO add your handling code here:
        
        this.txtInfo.setText(this.myParroquia.totalizarDiezmos());
        
    }//GEN-LAST:event_cmbTotalDiezmoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbBuscarFiel;
    private javax.swing.JButton cmbConsultarDiezmo;
    private javax.swing.JButton cmbEliminarFiel;
    private javax.swing.JComboBox<String> cmbEstrato;
    private javax.swing.JButton cmbGuardarFiel;
    private javax.swing.JButton cmbModificarFiel;
    private javax.swing.JButton cmbPagarDiezmo;
    private javax.swing.JButton cmbTotalDiezmo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCedulaFiel;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextArea txtInfo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtValorDiezmo;
    // End of variables declaration//GEN-END:variables
}
